In [1]:
import pandas as pd
from sklearn import linear_model
from matplotlib import pyplot as plt

In [47]:
df=pd.read_excel(r"C:\Users\kiran\OneDrive\logestic binary.xlsm")
dummies=pd.get_dummies(df['diagnosis'],dtype=int)
dummies.head()

   B  M
0  1  0
1  0  1
2  0  1
3  1  0
4  0  1

In [48]:
merged=pd.concat([df,dummies],axis='columns')
merged.head()

   radius  texture  perimeter     area diagnosis  B  M
0   13.30    17.36      37.31  1081.65         B  1  0
1   18.38    15.31      55.91  1218.05         M  0  1
2   20.45    20.42      58.60  1399.15         M  0  1
3    8.07    20.51      24.30   555.38         B  1  0
4   20.94    28.91      69.09  1333.29         M  0  1

In [50]:
final=merged.drop(['diagnosis','B'],axis='columns')
final.head()

   radius  texture  perimeter     area  M
0   13.30    17.36      37.31  1081.65  0
1   18.38    15.31      55.91  1218.05  1
2   20.45    20.42      58.60  1399.15  1
3    8.07    20.51      24.30   555.38  0
4   20.94    28.91      69.09  1333.29  1

In [51]:
x = final[['radius','texture','perimeter','area']]
y = final['M']

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [54]:
len(x_train)

96

In [55]:
x_train

     radius  texture  perimeter     area
1     18.38    15.31      55.91  1218.05
44    17.11    25.63      57.70  1424.24
81    12.16    29.81      41.19   948.86
102   19.66    15.82      64.15  1403.46
113   21.87    24.74      70.07  1835.72
..      ...      ...        ...      ...
40    16.40    11.15      52.13  1343.87
79    17.22    22.56      52.53  1156.36
80     8.42    12.23      26.77   615.34
36    15.45    11.14      53.74  1296.35
53    18.99    21.35      56.20  1708.43

[96 rows x 4 columns]

In [56]:
len(x_test)

24

In [57]:
len(y_train)

96

In [58]:
(y_train)

1      1
44     1
81     0
102    1
113    1
      ..
40     1
79     1
80     0
36     0
53     1
Name: M, Length: 96, dtype: int32

In [74]:
method=linear_model.LogisticRegression()

In [75]:
method.fit(x_train,y_train)

LogisticRegression()

In [77]:
method.predict(x_test)

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1])

In [78]:
method.predict_proba(x_test)

array([[4.69310613e-08, 9.99999953e-01],
       [9.99999991e-01, 8.66803484e-09],
       [9.99999999e-01, 6.28423963e-10],
       [7.20362868e-02, 9.27963713e-01],
       [2.25367991e-09, 9.99999998e-01],
       [9.13728021e-08, 9.99999909e-01],
       [2.15349797e-03, 9.97846502e-01],
       [1.47751795e-07, 9.99999852e-01],
       [9.99984323e-01, 1.56767388e-05],
       [8.49376082e-07, 9.99999151e-01],
       [1.59417720e-04, 9.99840582e-01],
       [4.19979607e-11, 1.00000000e+00],
       [9.99903614e-01, 9.63859792e-05],
       [3.49909069e-08, 9.99999965e-01],
       [1.16400223e-10, 1.00000000e+00],
       [1.22050549e-08, 9.99999988e-01],
       [3.12054476e-06, 9.99996879e-01],
       [9.99823341e-01, 1.76658876e-04],
       [9.92962461e-01, 7.03753890e-03],
       [9.99999988e-01, 1.18237508e-08],
       [9.31457978e-01, 6.85420215e-02],
       [7.57349822e-04, 9.99242650e-01],
       [9.99984054e-01, 1.59462528e-05],
       [4.32719981e-06, 9.99995673e-01]])